comment:
  layout: "diff"
  behavior: default
  require_changes: true # Post coverage comment only if coverage changes

coverage:
  status:
    project:
      default:
        # basic
        target: 85%
        threshold: 10%
        # advanced
        if_not_found: success
        if_ci_failed: error
        if_no_uploads: error
    patch:
      default:
        # basic
        target: 90%
        if_not_found: success
        if_ci_failed: error
        if_no_uploads: error
