# Define constants relating to the default/current version of System Coupling

SYC_MAJOR_VERSION = 23
SYC_MINOR_VERSION = 2

SYC_VERSION_CONCAT = f"{SYC_MAJOR_VERSION}{SYC_MINOR_VERSION}"
SYC_VERSION_DOT = f"{SYC_MAJOR_VERSION}.{SYC_MINOR_VERSION}"
SYC_VERSION_UNDERSCORE = f"{SYC_MAJOR_VERSION}_{SYC_MINOR_VERSION}"

SYC_DEFAULT_IMAGE_TAG = f"v{SYC_VERSION_DOT}.0"
