# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: output_stream.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='output_stream.proto',
  package='syc',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13output_stream.proto\x12\x03syc\"\x12\n\x10StdStreamRequest\"!\n\x11StdStreamResponse\x12\x0c\n\x04text\x18\x01 \x01(\t2V\n\x0cOutputStream\x12\x46\n\x11\x42\x65ginStdStreaming\x12\x15.syc.StdStreamRequest\x1a\x16.syc.StdStreamResponse\"\x00\x30\x01\x62\x06proto3'
)




_STDSTREAMREQUEST = _descriptor.Descriptor(
  name='StdStreamRequest',
  full_name='syc.StdStreamRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=46,
)


_STDSTREAMRESPONSE = _descriptor.Descriptor(
  name='StdStreamResponse',
  full_name='syc.StdStreamResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='syc.StdStreamResponse.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=81,
)

DESCRIPTOR.message_types_by_name['StdStreamRequest'] = _STDSTREAMREQUEST
DESCRIPTOR.message_types_by_name['StdStreamResponse'] = _STDSTREAMRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StdStreamRequest = _reflection.GeneratedProtocolMessageType('StdStreamRequest', (_message.Message,), {
  'DESCRIPTOR' : _STDSTREAMREQUEST,
  '__module__' : 'output_stream_pb2'
  # @@protoc_insertion_point(class_scope:syc.StdStreamRequest)
  })
_sym_db.RegisterMessage(StdStreamRequest)

StdStreamResponse = _reflection.GeneratedProtocolMessageType('StdStreamResponse', (_message.Message,), {
  'DESCRIPTOR' : _STDSTREAMRESPONSE,
  '__module__' : 'output_stream_pb2'
  # @@protoc_insertion_point(class_scope:syc.StdStreamResponse)
  })
_sym_db.RegisterMessage(StdStreamResponse)



_OUTPUTSTREAM = _descriptor.ServiceDescriptor(
  name='OutputStream',
  full_name='syc.OutputStream',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=83,
  serialized_end=169,
  methods=[
  _descriptor.MethodDescriptor(
    name='BeginStdStreaming',
    full_name='syc.OutputStream.BeginStdStreaming',
    index=0,
    containing_service=None,
    input_type=_STDSTREAMREQUEST,
    output_type=_STDSTREAMRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_OUTPUTSTREAM)

DESCRIPTOR.services_by_name['OutputStream'] = _OUTPUTSTREAM

# @@protoc_insertion_point(module_scope)
