# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: process.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='process.proto',
  package='syc',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rprocess.proto\x12\x03syc\"\r\n\x0bPingRequest\"\x0e\n\x0cPingResponse\"\r\n\x0bQuitRequest\"\x0e\n\x0cQuitResponse2g\n\x07Process\x12-\n\x04Ping\x12\x10.syc.PingRequest\x1a\x11.syc.PingResponse\"\x00\x12-\n\x04Quit\x12\x10.syc.QuitRequest\x1a\x11.syc.QuitResponse\"\x00\x62\x06proto3'
)




_PINGREQUEST = _descriptor.Descriptor(
  name='PingRequest',
  full_name='syc.PingRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=35,
)


_PINGRESPONSE = _descriptor.Descriptor(
  name='PingResponse',
  full_name='syc.PingResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=51,
)


_QUITREQUEST = _descriptor.Descriptor(
  name='QuitRequest',
  full_name='syc.QuitRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=66,
)


_QUITRESPONSE = _descriptor.Descriptor(
  name='QuitResponse',
  full_name='syc.QuitResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=82,
)

DESCRIPTOR.message_types_by_name['PingRequest'] = _PINGREQUEST
DESCRIPTOR.message_types_by_name['PingResponse'] = _PINGRESPONSE
DESCRIPTOR.message_types_by_name['QuitRequest'] = _QUITREQUEST
DESCRIPTOR.message_types_by_name['QuitResponse'] = _QUITRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PingRequest = _reflection.GeneratedProtocolMessageType('PingRequest', (_message.Message,), {
  'DESCRIPTOR' : _PINGREQUEST,
  '__module__' : 'process_pb2'
  # @@protoc_insertion_point(class_scope:syc.PingRequest)
  })
_sym_db.RegisterMessage(PingRequest)

PingResponse = _reflection.GeneratedProtocolMessageType('PingResponse', (_message.Message,), {
  'DESCRIPTOR' : _PINGRESPONSE,
  '__module__' : 'process_pb2'
  # @@protoc_insertion_point(class_scope:syc.PingResponse)
  })
_sym_db.RegisterMessage(PingResponse)

QuitRequest = _reflection.GeneratedProtocolMessageType('QuitRequest', (_message.Message,), {
  'DESCRIPTOR' : _QUITREQUEST,
  '__module__' : 'process_pb2'
  # @@protoc_insertion_point(class_scope:syc.QuitRequest)
  })
_sym_db.RegisterMessage(QuitRequest)

QuitResponse = _reflection.GeneratedProtocolMessageType('QuitResponse', (_message.Message,), {
  'DESCRIPTOR' : _QUITRESPONSE,
  '__module__' : 'process_pb2'
  # @@protoc_insertion_point(class_scope:syc.QuitResponse)
  })
_sym_db.RegisterMessage(QuitResponse)



_PROCESS = _descriptor.ServiceDescriptor(
  name='Process',
  full_name='syc.Process',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=84,
  serialized_end=187,
  methods=[
  _descriptor.MethodDescriptor(
    name='Ping',
    full_name='syc.Process.Ping',
    index=0,
    containing_service=None,
    input_type=_PINGREQUEST,
    output_type=_PINGRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Quit',
    full_name='syc.Process.Quit',
    index=1,
    containing_service=None,
    input_type=_QUITREQUEST,
    output_type=_QUITRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_PROCESS)

DESCRIPTOR.services_by_name['Process'] = _PROCESS

# @@protoc_insertion_point(module_scope)
