# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sycapi.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ansys.api.systemcoupling.v0.variant_pb2 as variant__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='sycapi.proto',
  package='syc',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0csycapi.proto\x12\x03syc\x1a\rvariant.proto\"\r\n\x0bPingRequest\"\x0e\n\x0cPingResponse\"\r\n\x0bQuitRequest\"\x0e\n\x0cQuitResponse\"\x84\x01\n\x0e\x43ommandRequest\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\x12*\n\x04\x61rgs\x18\x02 \x03(\x0b\x32\x1c.syc.CommandRequest.Argument\x1a\x35\n\x08\x41rgument\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x1b\n\x03val\x18\x02 \x01(\x0b\x32\x0e.utils.Variant\"1\n\x0f\x43ommandResponse\x12\x1e\n\x06result\x18\x01 \x01(\x0b\x32\x0e.utils.Variant\"@\n\x0c\x45rrorDetails\x12\x1b\n\x13\x65xception_classname\x18\x01 \x01(\t\x12\x13\n\x0bstack_trace\x18\x02 \x01(\t2\xa4\x01\n\x06SycApi\x12-\n\x04Ping\x12\x10.syc.PingRequest\x1a\x11.syc.PingResponse\"\x00\x12<\n\rInvokeCommand\x12\x13.syc.CommandRequest\x1a\x14.syc.CommandResponse\"\x00\x12-\n\x04Quit\x12\x10.syc.QuitRequest\x1a\x11.syc.QuitResponse\"\x00\x62\x06proto3')
  ,
  dependencies=[variant__pb2.DESCRIPTOR,])




_PINGREQUEST = _descriptor.Descriptor(
  name='PingRequest',
  full_name='syc.PingRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=49,
)


_PINGRESPONSE = _descriptor.Descriptor(
  name='PingResponse',
  full_name='syc.PingResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=65,
)


_QUITREQUEST = _descriptor.Descriptor(
  name='QuitRequest',
  full_name='syc.QuitRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=80,
)


_QUITRESPONSE = _descriptor.Descriptor(
  name='QuitResponse',
  full_name='syc.QuitResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=96,
)


_COMMANDREQUEST_ARGUMENT = _descriptor.Descriptor(
  name='Argument',
  full_name='syc.CommandRequest.Argument',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='syc.CommandRequest.Argument.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='val', full_name='syc.CommandRequest.Argument.val', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=178,
  serialized_end=231,
)

_COMMANDREQUEST = _descriptor.Descriptor(
  name='CommandRequest',
  full_name='syc.CommandRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='command', full_name='syc.CommandRequest.command', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='args', full_name='syc.CommandRequest.args', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_COMMANDREQUEST_ARGUMENT, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=99,
  serialized_end=231,
)


_COMMANDRESPONSE = _descriptor.Descriptor(
  name='CommandResponse',
  full_name='syc.CommandResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='syc.CommandResponse.result', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=233,
  serialized_end=282,
)


_ERRORDETAILS = _descriptor.Descriptor(
  name='ErrorDetails',
  full_name='syc.ErrorDetails',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='exception_classname', full_name='syc.ErrorDetails.exception_classname', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stack_trace', full_name='syc.ErrorDetails.stack_trace', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=284,
  serialized_end=348,
)

_COMMANDREQUEST_ARGUMENT.fields_by_name['val'].message_type = variant__pb2._VARIANT
_COMMANDREQUEST_ARGUMENT.containing_type = _COMMANDREQUEST
_COMMANDREQUEST.fields_by_name['args'].message_type = _COMMANDREQUEST_ARGUMENT
_COMMANDRESPONSE.fields_by_name['result'].message_type = variant__pb2._VARIANT
DESCRIPTOR.message_types_by_name['PingRequest'] = _PINGREQUEST
DESCRIPTOR.message_types_by_name['PingResponse'] = _PINGRESPONSE
DESCRIPTOR.message_types_by_name['QuitRequest'] = _QUITREQUEST
DESCRIPTOR.message_types_by_name['QuitResponse'] = _QUITRESPONSE
DESCRIPTOR.message_types_by_name['CommandRequest'] = _COMMANDREQUEST
DESCRIPTOR.message_types_by_name['CommandResponse'] = _COMMANDRESPONSE
DESCRIPTOR.message_types_by_name['ErrorDetails'] = _ERRORDETAILS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PingRequest = _reflection.GeneratedProtocolMessageType('PingRequest', (_message.Message,), {
  'DESCRIPTOR' : _PINGREQUEST,
  '__module__' : 'sycapi_pb2'
  # @@protoc_insertion_point(class_scope:syc.PingRequest)
  })
_sym_db.RegisterMessage(PingRequest)

PingResponse = _reflection.GeneratedProtocolMessageType('PingResponse', (_message.Message,), {
  'DESCRIPTOR' : _PINGRESPONSE,
  '__module__' : 'sycapi_pb2'
  # @@protoc_insertion_point(class_scope:syc.PingResponse)
  })
_sym_db.RegisterMessage(PingResponse)

QuitRequest = _reflection.GeneratedProtocolMessageType('QuitRequest', (_message.Message,), {
  'DESCRIPTOR' : _QUITREQUEST,
  '__module__' : 'sycapi_pb2'
  # @@protoc_insertion_point(class_scope:syc.QuitRequest)
  })
_sym_db.RegisterMessage(QuitRequest)

QuitResponse = _reflection.GeneratedProtocolMessageType('QuitResponse', (_message.Message,), {
  'DESCRIPTOR' : _QUITRESPONSE,
  '__module__' : 'sycapi_pb2'
  # @@protoc_insertion_point(class_scope:syc.QuitResponse)
  })
_sym_db.RegisterMessage(QuitResponse)

CommandRequest = _reflection.GeneratedProtocolMessageType('CommandRequest', (_message.Message,), {

  'Argument' : _reflection.GeneratedProtocolMessageType('Argument', (_message.Message,), {
    'DESCRIPTOR' : _COMMANDREQUEST_ARGUMENT,
    '__module__' : 'sycapi_pb2'
    # @@protoc_insertion_point(class_scope:syc.CommandRequest.Argument)
    })
  ,
  'DESCRIPTOR' : _COMMANDREQUEST,
  '__module__' : 'sycapi_pb2'
  # @@protoc_insertion_point(class_scope:syc.CommandRequest)
  })
_sym_db.RegisterMessage(CommandRequest)
_sym_db.RegisterMessage(CommandRequest.Argument)

CommandResponse = _reflection.GeneratedProtocolMessageType('CommandResponse', (_message.Message,), {
  'DESCRIPTOR' : _COMMANDRESPONSE,
  '__module__' : 'sycapi_pb2'
  # @@protoc_insertion_point(class_scope:syc.CommandResponse)
  })
_sym_db.RegisterMessage(CommandResponse)

ErrorDetails = _reflection.GeneratedProtocolMessageType('ErrorDetails', (_message.Message,), {
  'DESCRIPTOR' : _ERRORDETAILS,
  '__module__' : 'sycapi_pb2'
  # @@protoc_insertion_point(class_scope:syc.ErrorDetails)
  })
_sym_db.RegisterMessage(ErrorDetails)



_SYCAPI = _descriptor.ServiceDescriptor(
  name='SycApi',
  full_name='syc.SycApi',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=351,
  serialized_end=515,
  methods=[
  _descriptor.MethodDescriptor(
    name='Ping',
    full_name='syc.SycApi.Ping',
    index=0,
    containing_service=None,
    input_type=_PINGREQUEST,
    output_type=_PINGRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='InvokeCommand',
    full_name='syc.SycApi.InvokeCommand',
    index=1,
    containing_service=None,
    input_type=_COMMANDREQUEST,
    output_type=_COMMANDRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Quit',
    full_name='syc.SycApi.Quit',
    index=2,
    containing_service=None,
    input_type=_QUITREQUEST,
    output_type=_QUITRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SYCAPI)

DESCRIPTOR.services_by_name['SycApi'] = _SYCAPI

# @@protoc_insertion_point(module_scope)
