# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import ansys.api.systemcoupling.v0.sycapi_pb2 as sycapi__pb2


class SycApiStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Ping = channel.unary_unary(
        '/syc.SycApi/Ping',
        request_serializer=sycapi__pb2.PingRequest.SerializeToString,
        response_deserializer=sycapi__pb2.PingResponse.FromString,
        )
    self.InvokeCommand = channel.unary_unary(
        '/syc.SycApi/InvokeCommand',
        request_serializer=sycapi__pb2.CommandRequest.SerializeToString,
        response_deserializer=sycapi__pb2.CommandResponse.FromString,
        )
    self.Quit = channel.unary_unary(
        '/syc.SycApi/Quit',
        request_serializer=sycapi__pb2.QuitRequest.SerializeToString,
        response_deserializer=sycapi__pb2.QuitResponse.FromString,
        )


class SycApiServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Ping(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def InvokeCommand(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Quit(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SycApiServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Ping': grpc.unary_unary_rpc_method_handler(
          servicer.Ping,
          request_deserializer=sycapi__pb2.PingRequest.FromString,
          response_serializer=sycapi__pb2.PingResponse.SerializeToString,
      ),
      'InvokeCommand': grpc.unary_unary_rpc_method_handler(
          servicer.InvokeCommand,
          request_deserializer=sycapi__pb2.CommandRequest.FromString,
          response_serializer=sycapi__pb2.CommandResponse.SerializeToString,
      ),
      'Quit': grpc.unary_unary_rpc_method_handler(
          servicer.Quit,
          request_deserializer=sycapi__pb2.QuitRequest.FromString,
          response_serializer=sycapi__pb2.QuitResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'syc.SycApi', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
