name: 'Generate API'

description: 'Generate API for specified version'

inputs:
  image-tag:
    description: 'Docker image tag for version'
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Pull docker image
      run: make docker-pull
      shell: bash
      env:
        SYC_IMAGE_TAG: ${{ inputs.image-tag }}

    - name: Generate API code
      run: make generate-api
      shell: bash
      env:
        SYC_LAUNCH_CONTAINER: 1
        SYC_IMAGE_TAG: ${{ inputs.image-tag }}
