"""Sphinx documentation configuration file."""

from datetime import datetime
import os
import shutil
import subprocess
import time

from ansys_sphinx_theme import (
    ansys_favicon,
    ansys_logo_white,
    ansys_logo_white_cropped,
    get_version_match,
    latex,
    watermark,
)
import sphinx_gallery
import sphinx_gallery.gen_rst

from ansys.systemcoupling.core import EXAMPLES_PATH, __version__

# Project information
project = "ansys-systemcoupling-core"
copyright = f"(c) {datetime.now().year} ANSYS, Inc. All rights reserved"
author = "Ansys Inc."
release = version = __version__
cname = os.getenv("DOCUMENTATION_CNAME", "nocname.com")


# Sphinx extensions
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "numpydoc",
    "sphinx.ext.intersphinx",
    "sphinx_autodoc_typehints",
    "sphinx_copybutton",
    "sphinxemoji.sphinxemoji",
    "sphinx_gallery.gen_gallery",
]

# We can't build the gallery on GitHub as it requires full System Coupling
# runs (involving Fluent, MAPDL, etc). Therefore we "pre-build" the
# gallery locally as a development activity and commit the files in
# doc/source/examples that are generated by Sphinx Gallery.
#
# The original intention was that the GitHub doc build would then simply
# build from all the rst files in doc/source, completely avoiding the
# gallery build either by excluding "gen_gallery" or setting the
# "plot_gallery" option to False. This *almost* works, but the
# thumbnail page is not generated correctly.
#
# Instead, we keep "gen_gallery" and fool Sphinx Gallery into thinking that
# the examples are up to date by monkey patching the md5sum_is_current check.
# This runs the gallery generation, ensuring that it is done correctly,
# but avoids running the examples.
#
# This was suggested at:
#    https://github.com/sphinx-gallery/sphinx-gallery/issues/704

# The default is *not* to rebuild the gallery so, to build locally, ensure
# PYSYC_BUILD_SPHINX_GALLERY is set and then commit any resultant changes
# in doc/source/examples as required.

if os.environ.get("PYSYC_BUILD_SPHINX_GALLERY") is None:
    sphinx_gallery.gen_rst.md5sum_is_current = lambda *a, **k: True

# Intersphinx mapping
intersphinx_mapping = {
    "python": ("https://docs.python.org/3/", None),
    # kept here as an example
    # "scipy": ("https://docs.scipy.org/doc/scipy/reference", None),
    # "numpy": ("https://numpy.org/devdocs", None),
    # "matplotlib": ("https://matplotlib.org/stable", None),
    # "pandas": ("https://pandas.pydata.org/pandas-docs/stable", None),
    # "pyvista": ("https://docs.pyvista.org/", None),
}

# numpydoc configuration
numpydoc_show_class_members = False
numpydoc_xref_param_type = True

# Consider enabling numpydoc validation. See:
# https://numpydoc.readthedocs.io/en/latest/validation.html#
numpydoc_validate = True
numpydoc_validation_checks = {
    "GL06",  # Found unknown section
    "GL07",  # Sections are in the wrong order.
    "GL08",  # The object does not have a docstring
    "GL09",  # Deprecation warning should precede extended summary
    "GL10",  # reST directives {directives} must be followed by two colons
    "SS01",  # No summary found
    "SS02",  # Summary does not start with a capital letter
    # "SS03", # Summary does not end with a period
    "SS04",  # Summary contains heading whitespaces
    # "SS05", # Summary must start with infinitive verb, not third person
    "RT02",  # The first line of the Returns section should contain only the
    # type, unless multiple values are being returned"
}

# Favicon
html_favicon = ansys_favicon

# static path
html_static_path = ["_static"]

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The suffix(es) of source filenames.
source_suffix = ".rst"

# The master toctree document.
master_doc = "index"

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ["_build"]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False

# Copy button customization ---------------------------------------------------
# exclude traditional Python prompts from the copied code
copybutton_prompt_text = r">>> ?|\.\.\. "
copybutton_prompt_is_regexp = True

assert os.environ.get("PYSYC_DOC_BUILD_VERSION"), "PYSYC_DOC_BUILD_VERSION is not set!"


def make_replacements_for_versioned_class_refs(names):
    # returns Sphinx "substitutions" of the form
    # .. |<NAME>_ROOT_CLASS_REF| replace:: :class:`<name>_root<..path to <name>_root module>`

    api_path = (
        f"ansys.systemcoupling.core.adaptor.api_{os.environ['PYSYC_DOC_BUILD_VERSION']}"
    )

    name_root = lambda n: f"{n.lower()}_root"
    make_subst_name = lambda n: f"{n.upper()}_ROOT_CLASS_REF"
    make_class_ref = (
        lambda n: f"{name_root(n)}<{api_path}.{name_root(n)}.{name_root(n)}>"
    )

    make_subst = (
        lambda n: f".. |{make_subst_name(n)}| replace:: :class:`{make_class_ref(n)}`"
    )

    return "\n".join(make_subst(n) for n in names)


def _clean_up_example_folder(gallery_folder_name: str, example_name: str):

    # Uses "git clean" to clean out output files from the the last example
    # run. This removes everything except tracked files but will retain
    # modifications to tracked files.

    def ls_print(when: str, enabled: bool = True):
        if not enabled:
            return
        cmd = ["ls", "-lR", f"../examples/{gallery_folder_name}"]
        print(f"{when}: {cmd}:")
        output = subprocess.run(cmd, capture_output=True, text=True).stdout
        print(f"{output}\n")

    def backup_folder():
        # A potential issue is that if the gallery is being run locally and a new
        # example is under development and has not yet been committed to git, this
        # will be deleted by the cleanup. Therefore, as a safety measure, zip up
        # folder contents to a backup location in a sibling directory, "backup",
        # of the EXAMPLES_PATH directory.

        backup_dir = os.path.join(EXAMPLES_PATH, "..", "backup")
        if not os.path.exists(backup_dir):
            os.makedirs(backup_dir)

        backup_path = os.path.join(backup_dir, f"before_{example_name}.zip")
        count = 0
        while os.path.exists(backup_path):
            count += 1
            backup_path = os.path.join(backup_dir, f"before_{example_name}_{count}.zip")

        gallery_folder_path = os.path.join(
            os.getcwd(), "..", "examples", gallery_folder_name
        )
        shutil.make_archive(backup_path.replace(".zip", ""), "zip", gallery_folder_path)

    backup_folder()

    time.sleep(5)  # Allow a few seconds to be sure everything shut down
    ls_print("BEFORE git clean", enabled=False)
    subprocess.run(
        ["git", "clean", "-d", "-f", "--", f"../examples/{gallery_folder_name}"]
    )
    ls_print("AFTER git clean", enabled=False)


def _reset_example(gallery_conf, fname: str, when: str):
    example_name = fname.replace(".py", "")

    # Add any examples that need MAPDL to this list
    using_mapdl_examples = ["oscillating_plate"]

    # If the examples needs to run MAPDL in a container, launch it before
    # the example and remove it after. This is because it has been found
    # that connections between MAPDL and SystemCoupling cannot be established
    # if we attempt to reuse the container across multiple examples.
    using_mapdl_container = (
        example_name in using_mapdl_examples
        and os.environ.get("PYMAPDL_START_INSTANCE", "").lower() == "false"
        and "mapdl" in os.environ.get("DOCKER_IMAGE", "")
    )

    if when == "before":
        # We only have one gallery folder at the moment. If this changes, we
        # will have to use fname to figure out the correct one. This implies
        # script names will have to be unique across gallery folders.
        _clean_up_example_folder("00-systemcoupling", example_name)

        if using_mapdl_container:
            subprocess.run(
                ["docker", "compose", "-f", "mapdl-docker-compose.yml", "up", "-d"]
            )
            print("MAPDL container launched")
    else:
        if using_mapdl_container:
            subprocess.run(
                ["docker", "compose", "-f", "mapdl-docker-compose.yml", "down"]
            )
            print("MAPDL container removed")


rst_epilog = make_replacements_for_versioned_class_refs(("CASE", "SETUP", "SOLUTION"))

# -- Sphinx Gallery Options ---------------------------------------------------
sphinx_gallery_conf = {
    # path to your examples scripts
    "examples_dirs": ["../../examples/"],
    # path where to save gallery generated examples
    "gallery_dirs": ["examples"],
    # Pattern to search for example files
    "filename_pattern": r"\.py",
    # Remove the "Download all examples" button from the top level gallery
    "download_all_examples": False,
    # Sort gallery example by file name instead of number of lines (default)
    "within_subsection_order": "FileNameSortKey",
    # directory where function granular galleries are stored
    "backreferences_dir": None,
    # Modules for which function level galleries are created.  In
    "doc_module": "ansys-systemcoupling-core",
    "ignore_pattern": "flycheck*",
    "thumbnail_size": (350, 350),
    "reset_modules_order": "both",
    "reset_modules": (_reset_example),
    # "plot_gallery": False,
    # Suppress config comments like "sphinx_gallery_thumbnail_path" from being rendered
    "remove_config_comments": True,
    "abort_on_example_error": True,
}

# -- Options for warning control ---------------------------------------------

# Suppress warning about unpickleable function (reset_modules) element in sphinx_gallery_conf
suppress_warnings = ["config.cache"]


# -- Options for HTML output -------------------------------------------------
html_short_title = html_title = "PySystemCoupling"
html_theme = "ansys_sphinx_theme"
html_theme_options = {
    "logo": "pyansys",
    "github_url": "https://github.com/ansys/pysystem-coupling",
    "show_prev_next": False,
    "show_breadcrumbs": True,
    "use_edit_page_button": True,
    "additional_breadcrumbs": [
        ("PyAnsys", "https://docs.pyansys.com"),
    ],
    "navigation_depth": -1,
    "collapse_navigation": True,
    "icon_links": [
        {
            "name": "Support",
            "url": "https://github.com/ansys/pysystem-coupling/issues",
            "icon": "fa fa-comment fa-fw",
        },
        {
            "name": "Contribute",
            "url": "https://systemcoupling.docs.pyansys.com/version/dev/contributing.html",
            "icon": "fa fa-wrench",
        },
    ],
    "switcher": {
        "json_url": f"https://{cname}/versions.json",
        "version_match": get_version_match(__version__),
    },
}

html_context = {
    "display_github": True,  # Integrate GitHub
    "github_user": "pyansys",
    "github_repo": "pysystem-coupling",
    "github_version": "main",
    "doc_path": "doc/source",
    "source_path": "src",
}

# additional logos for the latex coverpage
latex_additional_files = [watermark, ansys_logo_white, ansys_logo_white_cropped]

# change the preamble of latex with customized title page
# variables are the title of pdf, watermark
latex_elements = {"preamble": latex.generate_preamble(html_title)}
