#
# This is an auto-generated file.  DO NOT EDIT!
#

from ansys.systemcoupling.core.adaptor.impl.types import *


class get_setup_summary(InjectedCommand):
    """
    Returns a string containing a formatted summary of the
    coupled analysis setup.

    This summary is printed in the System Coupling transcript
    output at the beginning of a solve. However, it is sometimes
    useful to see the summary before starting the solve

    The summary output is generated by System Coupling and is not
    modified for PySystemCoupling purposes. Any datamodel type names
    that are referenced in the summary therefore might not
    be fully consistent with PySystemCoupling conventions.
    """

    syc_name = "GetSetupSummary"

    cmd_name = "get_setup_summary"
